# 3 Pandas数据处理

In [1]:
import pandas as pd
import numpy as np
print(np.__version__)
print(pd.__version__)

1.14.5
0.23.1


## 3.2 Pandas对象简介

### 3.2.1 Pandas的Series对象

#### 1.Serise是通用的NumPy数组

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

#### 2.Series是特殊的字典

以Python创建字典的方式将字典传递给pd.Series()即可

#### 3.创建Series对象

```python
#之前的创建方式都是这种形式
    pd.Series(data, index = index)
#其中data可以是列表或者NumPy数组，这时index默认值为正数序列：```

In [7]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

~~~python
#data也可以是一个标量，创建Series对象时会重复填充到每个索引上：
~~~

In [8]:
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

~~~python
#data也可以是一个字典，index默认是排序的字典键：
~~~

In [9]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

### 3.2.2 Pandas的DataFrame对象

#### 1.DataFrame是通用的NumPy数组

如果将Series类比为带灵活索引的一维数组，那么DataFrame就可以看作是一种既有灵活的行索引，又有灵活列名的二维数组。就像你可以把二维数组看成是有序排列的一维数组一样，你也可以把DataFrame看成是有序排列的若干Series对象。这里的排列指的是他们有共同的索引。

#### 2.DataFrame是特殊的字典

~~~python
states['area'] #即可实现显示某一列 
~~~

#### 3.创建DataFrame对象

##### (1)通过单个Series对象创建。

~~~python
pd.DataFrame(population, columns = ['population'])~~~

##### (2)通过字典列表创建

In [10]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [11]:
#即使有些键不存在，Pandas也会用缺失值NaN来表示：
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

##### (3)通过Series对象字典创建

In [12]:
#pd.DataFrame({'population': population, 'area': area})

##### (4)通过NumPy二维数组创建

假如有一个二维数组，就可以创建一个可以指定行列索引值的DataFrame。如果不指定行列索引值，那么行列默认都是整数索引值：

In [13]:
import numpy as np
import pandas as pd
pd.DataFrame(np.random.rand(3, 2), 
             columns = ['foo', 'bar'], 
             index = ['a', 'b', 'c'])

foo       bar
a  0.620161  0.596156
b  0.388765  0.555965
c  0.789301  0.055187

##### (5)通过NumPy结构化数组创建

In [14]:
A = np.zeros(3, dtype = [('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [15]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

### 3.2.3 Pandas的Index对象

In [16]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

#### 1.将Index看作不可变数组

In [17]:
ind[1]

3

In [18]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [19]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [20]:
ind[1] = 0#Index对象的索引不可变

TypeError: Index does not support mutable operations

#### 2.将Index看作有序集合

In [22]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [23]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [24]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

## 3.3 数据取值与选择

### 3.3.1 Series数据选择方法

#### 1.将Series看作字典

In [26]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [27]:
data['b']

0.5

In [28]:
'a' in data

True

In [29]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [31]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [32]:
#用字典语法调整数据
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

#### 2.将Series看作一维数组

In [33]:
#将显式索引作为切片
data['a' : 'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [34]:
#将隐式整数索引作为切片
data[0:2]

a    0.25
b    0.50
dtype: float64

In [39]:
#掩码
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [40]:
#花哨的索引
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

>**切片是混乱之源！！！**

#### 3.索引器：loc、iloc和ix

In [41]:
data = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [42]:
data[1]#取值操作是显式索引

'a'

In [43]:
data[1:3]#切片操作是隐式索引

3    b
5    c
dtype: object

由于整数索引很容易造成混淆，所以Pandas提供了一些索引器(indexer)属性来作为取值的方法。

##### (1)第一种索引器是loc属性，表示取值和切片都是显式的：

In [44]:
data.loc[1]

'a'

In [45]:
data.loc[1:3]

1    a
3    b
dtype: object

##### (2)第二种索引器是iloc属性，表示取值和切片都是Python形式**(左闭右开)**的隐式索引：

In [46]:
data.iloc[1]

'b'

In [47]:
data.iloc[1:3]

3    b
5    c
dtype: object

##### (3)第三种属性是ix,他是前两种索引器的混合形式，在DataFrame对象中介绍

### 3.3.2 DataFrame数据选择方法

#### 1.把DataFrame看作字典

In [48]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [49]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [50]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [51]:
data['area'] is data.area

True

In [57]:
print(data['pop'])
print(data.pop)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64
<bound method NDFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>


In [59]:
#增加一列可以这样做：
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### 2.将DataFrame看作二维数组

In [60]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [61]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [63]:
data.values[0]#获取单个行数据

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [64]:
data['area']#获取单个列数据

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [65]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [66]:
data.loc[:'Illinois', : 'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [67]:
#使用ix索引器可以实现一种混合效果：
data.ix[:3, :'pop'] #被弃用了才是最骚的！！！hhh

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [68]:
#任何用于处理NumPy形式数据的方法都可以用于这些索引器：
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [70]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### 3.其他取值方法

In [75]:
#对单个标签取值就选择列，对多个标签用切片就选择行:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [77]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [78]:
#切片也可以不用索引值，而直接用行数来实现：
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [79]:
#与之类似，掩码也可以直接对每一行进行过滤，而不需要使用loc索引器
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

## 3.4 Pandas数值运算方法

### 3.4.1 通用函数：保留索引

In [80]:
import pandas as pd
import numpy as np

In [82]:
rng = np.random.RandomState(42)#设置随机数种子
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [83]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns = ['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

如果对这两个对象中的其中一个使用NumPy通用函数，生成的结果是另一个保留索引的Pandas对象：

In [86]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [89]:
#或者再做一个复杂的运算
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

### 3.4.2 通用函数：索引对齐

#### 1.Series索引对齐 

In [90]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [91]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

结果数组的索引是两个输入数组索引的并集，用集合运算法则来获得这个索引：

In [92]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [93]:
A = pd.Series([2, 4, 6], index = [0, 1, 2])
B = pd.Series([1, 3, 5], index = [1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [94]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

#### 2.DataFrame索引对齐

In [95]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns = list('AB'))
A

A   B
0  1  11
1  5   1

In [97]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns = list('BAC'))
B

B  A  C
0  3  8  2
1  4  2  6
2  4  8  6

In [98]:
A + B

A     B   C
0  9.0  14.0 NaN
1  7.0   5.0 NaN
2  NaN   NaN NaN

In [99]:
A.add(B, fill_value = 0)

A     B    C
0  9.0  14.0  2.0
1  7.0   5.0  6.0
2  8.0   4.0  6.0

In [100]:
fill = A.stack().mean()
A.add(B, fill_value = fill)

A     B     C
0   9.0  14.0   6.5
1   7.0   5.0  10.5
2  12.5   8.5  10.5

### 3.4.3 通用函数：DataFrame与Series的运算

In [103]:
A = rng.randint(10, size = (3, 4))
A

array([[2, 0, 3, 1],
       [7, 3, 1, 5],
       [5, 9, 3, 5]])

In [104]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 5,  3, -2,  4],
       [ 3,  9,  0,  4]])

In [105]:
df = pd.DataFrame(A, columns = list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  5  3 -2  4
2  3  9  0  4

In [108]:
df.sub(df['R'], axis = 0)

Q  R  S  T
0  2  0  3  1
1  4  0 -2  2
2 -4  0 -6 -4

In [112]:
halfrow = df.iloc[0, ::2]
halfrow

Q    2
S    3
Name: 0, dtype: int32

In [113]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  5.0 NaN -2.0 NaN
2  3.0 NaN  0.0 NaN

## 3.5 处理缺失值

### 3.5.1 选择处理缺失值的方法

#### 1.None：Python对象类型的缺失值 

In [118]:
vals1 = np.array([1, None, 3, 4])
vals1#**慢**

array([1, None, 3, 4], dtype=object)

#### 2.NaN：数值类型的缺失值

In [119]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype#**快**

dtype('float64')

#### 3.Pandas中NaN与None的差异

In [120]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

### 3.5.3 处理缺失值

#### 1.发现缺失值

In [121]:
data = pd.Series([1, np.nan, 'hello', None])

In [122]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [124]:
data[data.notnull()]

0        1
2    hello
dtype: object

#### 2.剔除缺失值

In [125]:
data.dropna()

0        1
2    hello
dtype: object

In [126]:
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, 5],
                  [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [127]:
#默认删除整行
df.dropna()

0    1  2
1  2.0  3.0  5

In [128]:
df.dropna(axis = 'columns')

2
0  2
1  5
2  6

In [129]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [134]:
df.dropna(axis = 1, how = 'all')

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [135]:
df.dropna(axis = 'rows', thresh = 3)

0    1  2   3
1  2.0  3.0  5 NaN

#### 3.填充缺失值

In [136]:
data = pd.Series([1, np.nan, 2, None, 3], index = list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [137]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [139]:
data.fillna(method = 'ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [140]:
data.fillna(method = 'bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [141]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [144]:
df.fillna(method = 'ffill', axis = 1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0